services:
  web:
    build: .
    container_name: nagaDocker_web
    ports:
      - "8000:80"
    volumes:
      - ./www:/var/www/html
      - ./classes:/var/www/classes
      - ./php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db

  db:
    image: mariadb:10.6
    container_name: nagaDocker_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nagadb
      MYSQL_USER: nagauser
      MYSQL_PASSWORD: nagapassword
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: nagaDocker_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  mysql_data:
